import type { AssetClass, ProviderDescriptor } from "./types";

// ─── Provider registry ───────────────────────────────────────────────────────
// Declarative description of every market-data provider the terminal knows.
// Implemented adapters have real fetch code in providers/. Future-ready stubs
// declare their requirements so the architecture can be upgraded without rewrite.
// AI providers are analysis-only and must NEVER serve prices.

export const PROVIDERS: ProviderDescriptor[] = [

  // ── Implemented: no key, public feeds ────────────────────────────────────────

  {
    id: "yahoo",
    name: "Yahoo Finance (Delayed)",
    assetClasses: ["equity", "etf"],
    capabilities: ["quotes"],
    envVars: [],
    requiresKey: false,
    requiresGateway: false,
    isTradingCapable: false,
    readOnly: true,
    priority: 20,
    liveCapable: false,
    isDelayed: true,
    implemented: true,
    sourceLabel: "Delayed · Yahoo",
    description: "Free public delayed (~15 min) equity & ETF quotes. Never labeled live.",
  },
  {
    id: "coingecko",
    name: "CoinGecko",
    assetClasses: ["crypto"],
    capabilities: ["quotes"],
    envVars: [],
    requiresKey: false,
    requiresGateway: false,
    isTradingCapable: false,
    readOnly: true,
    priority: 20,
    liveCapable: false,
    isDelayed: false,
    implemented: true,
    sourceLabel: "CoinGecko · Reference",
    description: "Free public crypto reference prices (BTC, ETH, SOL, SUI). Near real-time, labeled reference.",
  },
  {
    id: "kraken",
    name: "Kraken",
    assetClasses: ["crypto"],
    capabilities: ["quotes"],
    envVars: [],
    requiresKey: false,
    requiresGateway: false,
    isTradingCapable: true,
    readOnly: true,
    priority: 12,
    liveCapable: true,
    isDelayed: false,
    implemented: true,
    sourceLabel: "Live · Kraken",
    description: "Public Kraken exchange ticker (no key required). Real-time crypto prices.",
  },
  {
    id: "coinbase",
    name: "Coinbase",
    assetClasses: ["crypto"],
    capabilities: ["quotes"],
    envVars: [],
    requiresKey: false,
    requiresGateway: false,
    isTradingCapable: true,
    readOnly: true,
    priority: 14,
    liveCapable: true,
    isDelayed: false,
    implemented: true,
    sourceLabel: "Live · Coinbase",
    description: "Public Coinbase Exchange stats (no key required). Real-time crypto prices.",
  },

  // ── Implemented: keyed providers ─────────────────────────────────────────────
  // Adapters are real; fetchers self-check env vars and fall through when absent.

  {
    id: "moomoo",
    name: "MooMoo / OpenD",
    assetClasses: ["equity", "etf", "crypto"],
    capabilities: ["quotes", "trading"],
    envVars: ["MOOMOO_OPEND_HOST", "MOOMOO_OPEND_PORT"],
    requiresKey: false,
    requiresGateway: true,
    isTradingCapable: true,
    readOnly: true,
    priority: 5,
    liveCapable: true,
    isDelayed: false,
    implemented: false,
    sourceLabel: "Live · MooMoo",
    description: "Live quotes via local OpenD gateway. Requires reachable OpenD host. Trading locked READ-ONLY.",
  },
  {
    id: "alpaca",
    name: "Alpaca Markets",
    assetClasses: ["equity", "etf"],
    capabilities: ["quotes"],
    envVars: ["ALPACA_API_KEY", "ALPACA_API_SECRET"],
    requiresKey: true,
    requiresGateway: false,
    isTradingCapable: true,
    readOnly: true,
    priority: 8,
    liveCapable: false,
    isDelayed: true,
    implemented: true,
    sourceLabel: "Delayed · Alpaca",
    description: "IEX-feed delayed quotes. Requires ALPACA_API_KEY + ALPACA_API_SECRET. Trading locked READ-ONLY.",
  },
  {
    id: "polygon",
    name: "Polygon.io",
    assetClasses: ["equity", "etf"],
    capabilities: ["quotes"],
    envVars: ["POLYGON_API_KEY"],
    requiresKey: true,
    requiresGateway: false,
    isTradingCapable: false,
    readOnly: true,
    priority: 10,
    liveCapable: true,
    isDelayed: true,
    implemented: true,
    sourceLabel: "Delayed · Polygon",
    description: "Snapshot quotes (delayed free / real-time paid). Requires POLYGON_API_KEY.",
  },
  {
    id: "fmp",
    name: "Financial Modeling Prep",
    assetClasses: ["equity", "etf", "fundamentals"],
    capabilities: ["quotes", "fundamentals"],
    envVars: ["FMP_API_KEY"],
    requiresKey: true,
    requiresGateway: false,
    isTradingCapable: false,
    readOnly: true,
    priority: 15,
    liveCapable: false,
    isDelayed: true,
    implemented: true,
    sourceLabel: "Delayed · FMP",
    description: "Quotes + fundamentals (delayed on free tier). Requires FMP_API_KEY.",
  },

  // ── Future-ready stubs ────────────────────────────────────────────────────────

  {
    id: "sec_edgar",
    name: "SEC EDGAR",
    assetClasses: ["fundamentals"],
    capabilities: ["filings", "fundamentals"],
    envVars: [],
    requiresKey: false,
    requiresGateway: false,
    isTradingCapable: false,
    readOnly: true,
    priority: 30,
    liveCapable: false,
    isDelayed: false,
    implemented: false,
    sourceLabel: "SEC EDGAR",
    description: "Official company filings & fundamentals. Never a price source.",
  },

  // ── AI providers — ANALYSIS ONLY, never a market-data source ─────────────────

  {
    id: "openai",
    name: "OpenAI",
    assetClasses: ["ai"],
    capabilities: ["analysis"],
    envVars: ["OPENAI_API_KEY"],
    requiresKey: true,
    requiresGateway: false,
    isTradingCapable: false,
    readOnly: true,
    priority: 100,
    liveCapable: false,
    isDelayed: false,
    implemented: false,
    sourceLabel: "AI · OpenAI",
    description: "Analysis & summarization only. Never used as a price source.",
  },
  {
    id: "perplexity",
    name: "Perplexity",
    assetClasses: ["ai"],
    capabilities: ["analysis"],
    envVars: ["PERPLEXITY_API_KEY"],
    requiresKey: true,
    requiresGateway: false,
    isTradingCapable: false,
    readOnly: true,
    priority: 100,
    liveCapable: false,
    isDelayed: false,
    implemented: false,
    sourceLabel: "AI · Perplexity",
    description: "Research synthesis only. Never used as a price source.",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    assetClasses: ["ai"],
    capabilities: ["analysis"],
    envVars: ["DEEPSEEK_API_KEY"],
    requiresKey: true,
    requiresGateway: false,
    isTradingCapable: false,
    readOnly: true,
    priority: 100,
    liveCapable: false,
    isDelayed: false,
    implemented: false,
    sourceLabel: "AI · DeepSeek",
    description: "Analysis only. Never used as a price source.",
  },
  {
    id: "gemini",
    name: "Google Gemini",
    assetClasses: ["ai"],
    capabilities: ["analysis"],
    envVars: ["GEMINI_API_KEY"],
    requiresKey: true,
    requiresGateway: false,
    isTradingCapable: false,
    readOnly: true,
    priority: 100,
    liveCapable: false,
    isDelayed: false,
    implemented: false,
    sourceLabel: "AI · Gemini",
    description: "Analysis only. Never used as a price source.",
  },
];

export function getProvider(id: string): ProviderDescriptor | undefined {
  return PROVIDERS.find((p) => p.id === id);
}

// Providers that can serve quotes for an asset class, sorted highest-priority first.
// Includes both implemented and unimplemented providers (router filters by implemented).
export function quoteProvidersFor(assetClass: AssetClass): ProviderDescriptor[] {
  return PROVIDERS.filter(
    (p) =>
      p.assetClasses.includes(assetClass) &&
      p.capabilities.includes("quotes"),
  ).sort((a, b) => a.priority - b.priority);
}
